---
- name: Configure iptables
  hosts: rhel8
  become: true
  gather_facts: true
  tasks:
    - name: Verify iptables and iptables-services are installed
      stat:
        path: /usr/sbin/iptables
      register: iptables_check
      ignore_errors: true

    - name: Install iptables and iptables-services
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - iptables
        - iptables-services
      when: iptables_check.stat.exists == false
      ignore_errors: true

    - name: Stop firewalld service
      systemd:
        name: firewalld
        state: stopped
      ignore_errors: true

    - name: Stop nftables service
      systemd:
        name: nftables
        state: stopped
      ignore_errors: true

    - name: Start and enable iptables service
      systemd:
        name: iptables
        state: started
        enabled: yes
      ignore_errors: true

    - name: Flush all firewall rules
      iptables:
        chain: "{{ item }}"
        policy: accept
        action: flush
      loop:
        - INPUT
        - OUTPUT
        - FORWARD
      ignore_errors: true

    - name: Allow incoming SSH traffic from specific IP
      iptables:
        chain: INPUT
        source: 192.168.73.130
        protocol: tcp
        dport: 22
        jump: ACCEPT
      ignore_errors: true

    - name: Allow incoming ICMP traffic with rate limiting
      iptables:
        chain: INPUT
        protocol: icmp
        icmp_type: echo-request
        limit: "1/s"
        jump: ACCEPT
      ignore_errors: true

    - name: Allow incoming HTTP (port 80) traffic
      iptables:
        chain: INPUT
        protocol: tcp
        dport: 80
        jump: ACCEPT
      ignore_errors: true

    - name: Allow incoming HTTPS (port 443) traffic
      iptables:
        chain: INPUT
        protocol: tcp
        dport: 443
        jump: ACCEPT
      ignore_errors: true

    - name: Set default policy for INPUT chain to DROP
      iptables:
        chain: INPUT
        policy: DROP
      ignore_errors: true

    - name: Set default policy for OUTPUT chain to ACCEPT
      iptables:
        chain: OUTPUT
        policy: ACCEPT
      ignore_errors: true

    - name: Allow existing connections (related and established)
      iptables:
        chain: INPUT
        ctstate: "{{ item }}"
        jump: ACCEPT
      loop:
        - RELATED,ESTABLISHED
      ignore_errors: true
