---
- name: Configure iptables on RHEL8
  hosts: rhel8
  become: true
  gather_facts: true
  tasks:
    - name: Verify iptables and iptables-services are installed
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - iptables
        - iptables-services
      ignore_errors: yes

    - name: Stop firewalld service
      service:
        name: firewalld
        state: stopped
      ignore_errors: yes

    - name: Stop nftables service
      service:
        name: nftables
        state: stopped
      ignore_errors: yes

    - name: Start and enable iptables service
      service:
        name: iptables
        state: started
        enabled: yes

    - name: Flush all firewall rules
      iptables:
        chain: "{{ item }}"
        policy: accept
        flush: yes
      loop:
        - INPUT
        - OUTPUT
        - FORWARD
      ignore_errors: yes

    - name: Allow incoming SSH traffic from specific IP
      iptables:
        chain: INPUT
        source: 192.168.73.130
        protocol: tcp
        dport: 22
        jump: ACCEPT
      ignore_errors: yes

    - name: Enable ICMP traffic with rate limiting
      iptables:
        chain: INPUT
        protocol: icmp
        limit: "1/s"
        jump: ACCEPT
      ignore_errors: yes

    - name: Allow incoming HTTP (port 80) traffic
      iptables:
        chain: INPUT
        protocol: tcp
        dport: 80
        jump: ACCEPT
      ignore_errors: yes

    - name: Allow incoming HTTPS (port 443) traffic
      iptables:
        chain: INPUT
        protocol: tcp
        dport: 443
        jump: ACCEPT
      ignore_errors: yes

    - name: Set default policies
      iptables:
        chain: "{{ item.chain }}"
        policy: "{{ item.policy }}"
      loop:
        - { chain: INPUT, policy: DROP }
        - { chain: FORWARD, policy: DROP }
        - { chain: OUTPUT, policy: ACCEPT }
      ignore_errors: yes
