---
- name: Configure iptables on RHEL8
  hosts: rhel8
  become: true
  tasks:
    - name: Install iptables and iptables-services
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - iptables
        - iptables-services
      ignore_errors: yes

    - name: Stop firewalld service
      service:
        name: firewalld
        state: stopped
      ignore_errors: yes

    - name: Stop nftables service
      service:
        name: nftables
        state: stopped
      ignore_errors: yes

    - name: Start and enable iptables service
      service:
        name: iptables
        state: started
        enabled: yes
      ignore_errors: yes

    - name: Flush all firewall rules
      command: iptables -F
      ignore_errors: yes

    - name: Allow incoming SSH traffic from specific IP
      iptables:
        chain: INPUT
        source: 192.168.73.130
        protocol: tcp
        destination_port: 22
        jump: ACCEPT
      ignore_errors: yes

    - name: Allow ICMP traffic with rate limiting
      iptables:
        chain: INPUT
        protocol: icmp
        match: icmp --icmp-type 8
        limit: "1/s"
        jump: ACCEPT
      ignore_errors: yes

    - name: Allow incoming HTTP (port 80) traffic
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        jump: ACCEPT
      ignore_errors: yes

    - name: Allow incoming HTTPS (port 443) traffic
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 443
        jump: ACCEPT
      ignore_errors: yes

    - name: Set default policy DROP for INPUT chain
      iptables:
        chain: INPUT
        policy: DROP
      ignore_errors: yes

    - name: Set default policy ACCEPT for OUTPUT chain
      iptables:
        chain: OUTPUT
        policy: ACCEPT
      ignore_errors: yes
...
