---
- name: Disable IP forwarding on RHEL8
  hosts: rhel8
  become: true
  tasks:
    - name: Disable IPv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 0
        state: present
      tags:
        - ipv4

    - name: Disable IPv6 forwarding
      sysctl:
        name: net.ipv6.conf.all.forwarding
        value: 0
        state: present
      tags:
        - ipv6
...
