---
- name: Ensure IP forwarding is disabled on RHEL 8
  hosts: rhel8
  become: true

  tasks:
    - name: Disable IPv4 forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 0
        state: present
        sysctl_set: true
        sysctl_file: /etc/sysctl.conf

    - name: Disable IPv6 forwarding
      sysctl:
        name: net.ipv6.conf.all.forwarding
        value: 0
        state: present
        sysctl_set: true
        sysctl_file: /etc/sysctl.conf

  handlers:
    - name: Restart Network
      service:
        name: network
        state: restarted
...