---
- name: Disable IP forwarding on RHEL8
  hosts: rhel8
  become: yes
  tasks:
    - name: Disable IPv4 forwarding permanently
      sysctl:
        name: net.ipv4.ip_forward
        value: 0
        state: present
      become_method: sudo

    - name: Disable IPv6 forwarding permanently
      sysctl:
        name: net.ipv6.conf.all.forwarding
        value: 0
        state: present
      become_method: sudo

    - name: Save sysctl configuration
      command: sysctl --system
      become_method: sudo

...
