---
- name: Harden Password Policies on RHEL 8
  hosts: rhel8
  become: yes
  tasks:
    - name: Enforce Minimum Password Length
      lineinfile:
        path: /etc/security/pwquality.conf
        line: "minlen = 14"
        insertafter: '^# minlen'
      ignore_errors: yes

    - name: Require Minimum Number of Character Classes
      lineinfile:
        path: /etc/security/pwquality.conf
        line: "minclass = 4"
        insertafter: '^# minclass'
      ignore_errors: yes

    - name: Limit Retry Attempts before Account Lock
      lineinfile:
        path: /etc/security/pwquality.conf
        line: "maxretry = 3"
        insertafter: '^# maxretry'
      ignore_errors: yes

    - name: Set Delay for Account Unlock
      lineinfile:
        path: /etc/security/pwquality.conf
        line: "retrydelay = 600"
        insertafter: '^# retrydelay'
      ignore_errors: yes

    - name: Prevent Password Reuse for Multiple Generations
      lineinfile:
        path: /etc/security/opasswd
        line: "password requisite pam_pwhistory.so remember=5"
        insertafter: '^# password requisite pam_pwhistory.so'
      ignore_errors: yes

    - name: Configure Password History Enforcement
      lineinfile:
        path: /etc/security/pwquality.conf
        line: "minclass = 4"
        insertafter: '^# minclass'
      ignore_errors: yes

    - name: Refresh PAM Configuration
      command: pam_tally2 --reset
      ignore_errors: yes
...
