---
- name: Configure sudoers for password-based privilege escalation
  hosts: rhel8
  become: true
  tasks:
    - name: Remove NOPASSWD lines from sudoers
      lineinfile:
        path: /etc/sudoers
        regexp: '^\s%wheel\s+ALL=\(ALL\)\s+NOPASSWD:'
        state: absent
      ignore_errors: yes

    - name: Replace NOPASSWD with PASSWD in sudoers
      lineinfile:
        path: /etc/sudoers
        regexp: '^\s%wheel\s+ALL=\(ALL\)\s+NOPASSWD:'
        line: '%wheel ALL=(ALL) PASSWD: ALL'
      ignore_errors: yes
