---
- name: Verify and install sudo on RHEL8
  hosts: rhel8
  become: yes
  tasks:
    - name: Check if sudo is installed
      become: no
      command: "which sudo"
      register: sudo_check_result
      ignore_errors: yes

    - name: Install sudo package
      become: yes
      package:
        name: sudo
        state: present
      when: sudo_check_result.rc != 0
...