---
- name: Configure filesystem integrity using AIDE tool
  hosts: rhel8
  ignore_errors: yes
  become: true

  tasks:
    - name: Install AIDE package
      yum:
        name: aide
        state: present

    - name: Copy AIDE configuration file
      copy:
        src: /etc/aide/aide.conf
        dest: /etc/aide/aide.conf.orig
        owner: root
        group: root
        mode: '0644'
      when: ansible_distribution_major_version == '8'

    - name: Configure AIDE cron job
      cron:
        name: Run AIDE integrity check
        minute: 0
        hour: 5
        job: /usr/sbin/aide --check
      when: ansible_distribution_major_version == '8'
...