---
- name: Configure iptables on RHEL 8
  hosts: rhel8
  become: true
  tasks:
    - name: Flush existing iptables rules
      command: iptables -F
      ignore_errors: yes

    - name: Set default policies
      command: iptables -P INPUT DROP
      ignore_errors: yes
    - command: iptables -P OUTPUT ACCEPT
      ignore_errors: yes

    - name: Allow ICMP (ping) traffic with rate limiting
      command: iptables -A INPUT -p icmp --icmp-type echo-request -m limit --limit 1/s -j ACCEPT
      ignore_errors: yes

    - name: Allow SSH traffic from the manager machine
      command: iptables -A INPUT -p tcp -s 192.168.73.130 --dport 22 -j ACCEPT
      ignore_errors: yes

    - name: Allow HTTP traffic (port 80)
      command: iptables -A INPUT -p tcp --dport 80 -j ACCEPT
      ignore_errors: yes

    - name: Allow HTTPS traffic (port 443)
      command: iptables -A INPUT -p tcp --dport 443 -j ACCEPT
      ignore_errors: yes

    # Any additional rules can be added here

    - name: Save iptables rules
      command: iptables-save > /etc/sysconfig/iptables
      ignore_errors: yes
...