---
- name: Disable IP forwarding on RHEL 8
  hosts: rhel8
  become: true

  tasks:
    - name: Disable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: 0
        state: present
      notify: Restart Network

  handlers:
    - name: Restart Network
      service:
        name: network
        state: restarted
...