---
- name: Ensure password expiration is 365 days or less
  hosts: rhel8
  become: yes
  tasks:
    - name: Update password expiration for specific users
      lineinfile:
        path: /etc/login.defs
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: yes
      with_items:
        - { regexp: '^PASS_MAX_DAYS\s+', line: 'PASS_MAX_DAYS   365' }
    - name: Change password expiration for root, ansible, and luigi
      user:
        name: "{{ item }}"
        max_password_age: 365
      with_items:
        - root
        - ansible
        - luigi
...