---
- name: Ensure re-authentication for privilege escalation is not disabled globally
  hosts: rhel8
  become: yes
  tasks:
    - name: Check /etc/sudoers file for "!authenticate" tag
      command: grep '!authenticate' /etc/sudoers
      register: sudoers_grep_result
      ignore_errors: yes

    - name: Remove "!authenticate" from /etc/sudoers file
      lineinfile:
        path: /etc/sudoers
        state: absent
        regexp: '!authenticate'
      when: sudoers_grep_result.rc == 0

    - name: Gather files in /etc/sudoers.d directory
      find:
        paths: /etc/sudoers.d
        file_type: file
      register: sudoers_d_files

    - name: Check sudoers.d files for "!authenticate" tag
      command: grep '!authenticate' "{{ item.path }}"
      register: sudoers_d_grep_result
      ignore_errors: yes
      loop: "{{ sudoers_d_files.files }}"

    - name: Remove "!authenticate" from sudoers.d files
      lineinfile:
        path: "{{ item.item.path }}"
        state: absent
        regexp: '!authenticate'
      when: item.rc == 0
      loop: "{{ sudoers_d_grep_result.results }}"
...