---
- name: Set password expiration day to 365 days or less
  hosts: rhel8
  become: yes
  ignore_errors: yes
  gather_facts: yes

  tasks:
    - name: Set password expiration for root
      ignore_errors: yes
      ansible.builtin.user:
        name: root
        password_expire_max: 365

    - name: Set password expiration for ansible
      ignore_errors: yes
      ansible.builtin.user:
        name: ansible
        password_expire_max: 365

    - name: Set password expiration for luigi
      ignore_errors: yes
      ansible.builtin.user:
        name: luigi
        password_expire_max: 365

    - name: Update /etc/login.defs
      ignore_errors: yes
      ansible.builtin.lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MAX_DAYS'
        line: 'PASS_MAX_DAYS   365'

...

