---
- name: Ensure password expiration day is 365 days or less
  hosts: rhel8
  become: yes
  ignore_errors: yes
  gather_facts: yes

  tasks:
    - name: Set password expiration for root user
      ansible.builtin.user:
        name: root
        password_expire_max: 365
      ignore_errors: yes

    - name: Set password expiration for ansible user
      ansible.builtin.user:
        name: ansible
        password_expire_max: 365
      ignore_errors: yes

    - name: Set password expiration for luigi user
      ansible.builtin.user:
        name: luigi
        password_expire_max: 365
      ignore_errors: yes

    - name: Update /etc/login.defs file
      ansible.builtin.lineinfile:
        path: /etc/login.defs
        regexp: '^PASS_MAX_DAYS'
        line: 'PASS_MAX_DAYS 365'
      ignore_errors: yes
...